### ISSUE TITLE
Get line/position number of capture

### ISSUE THREAD

**Issue by Varriount** [zevv/npeg#8]
If possible, it would be nice to get some meta-information about a capture, such as the position it is located at in the passed-in input.

**Comment by zevv** [comment]
Quoting Varriount (2019-06-01 09:41:19)

> If possible, it would be nice to get some meta-information about a
> capture, such as the position it is located at in the passed-in input.

Strictly speaking, the info is already available, although not exposed
through a documented API: The `MatchResult` type has a seq of `Capture`,
of which the `si` field is the offset in the subject string. Any
suggestions for how to properly expose this to the caller?



--
:wq
^X^Cy^K^X^C^C^C^C

**Comment by Varriount** [comment]
I wonder if it wouldn't be better, going forward, to have an actual "Capture" type exposed in code blocks, rather than the pure string data. It might be a breaking change, however it would make extending captures much easier, going forward.

**Comment by zevv** [comment]
Quoting Varriount (2019-06-02 05:43:00)

> I wonder if it wouldn't be better, going forward, to have an actual
> "Capture" type exposed in code blocks, rather than the pure string
> data. It might be a breaking change, however it would make extending
> captures much easier, going forward.

Not a bad idea. The breaking would be minimal, as we can just keep the
$-notation alive, it's just a slightly different rewrite. I'll give that
a try to see if it all fits nicely.

--
:wq
^X^Cy^K^X^C^C^C^C

**Comment by zevv** [comment]
Would the https://github.com/zevv/npeg/tree/capture-data branch work for you?

**Comment by Varriount** [comment]
Thoughts:
- A possible optimization would be to only create the captured string when it's actually required (so if a capture isn't used, a performance penalty isn't incurred).
- Wouldn't the convention be to have a `$` operator for the capture object, rather than an attribute? This would also make the previous point more doable.
- Even with this, I unfortunately can't think of an easy/efficient way to get what line a token occurred on.

**Comment by zevv** [comment]
Thanks for the feedback, very nice to have some review and comments,
especially to make me rethink choices I made long ago.

Quoting Varriount (2019-06-02 18:58:01)

> - A possible optimization would be to only create the captured string
> when it's actually required (so if a capture isn't used, a performance
> penalty isn't incurred).

You're absolutely right, and I would love that, but: this requires the
original subject string to be available when slicing the captures. So
either NPeg needs to keep a copy of the subject in the MatchResult after
matching (Copying is not nice performance- and memory-wise, and making a
shallow copy is tricky because there is no telling if the source string
gets modified by the caller between the match() call and when extracting
the captures) or the user needs to pass the subject again. Which is a
pita and suffers from the same might-be-modified-problem as above.

> - Wouldn't the convention be to have a `$` operator for the capture
> object, rather than an attribute? This would also make the previous
> point more doable.

That can be provided of course. But I'm afraid more confusion will
happen here because of the choice (mistake?) I made earlier by having
the sugar `$n` syntax count from 1 instead of from 0. So `$1` means
`$capure[0]`, argh.

> - Even with this, I unfortunately can't think of an easy/efficient way
> to get what line a token occurred on.

NPeg could of course keep track of line numbers for you, but that comes
at a performance cost at match time, which is probably not worth it.

It is not hard to do post-matching, but it requires you to pass over the
subject string another time to count the CR and/or LF occurences up to
the match offset. It makes sense to add a helper for this to NPeg, as
this migh be a common operation. 

--
:wq
^X^Cy^K^X^C^C^C^C
